//
// CharacterListInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CharacterListInfo: Codable, JSONEncodable, Hashable {

    public var count: Double
    public var pages: Double
    public var next: String
    public var prev: String?

    public init(count: Double, pages: Double, next: String, prev: String) {
        self.count = count
        self.pages = pages
        self.next = next
        self.prev = prev
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case pages
        case next
        case prev
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(count, forKey: .count)
        try container.encode(pages, forKey: .pages)
        try container.encode(next, forKey: .next)
        try container.encode(prev, forKey: .prev)
    }
}

